# CMake generated Testfile for 
# Source directory: /Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples
# Build directory: /Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.40-time-probe-example-default")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;1;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.40-gnuplot-example-default")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.40-double-probe-example-default")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.40-gnuplot-aggregator-example-default")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.40-gnuplot-helper-example-default")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.40-file-aggregator-example-default")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.40-file-helper-example-default")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/stats/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;20;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/stats/examples/CMakeLists.txt;0;")
