# CMake generated Testfile for 
# Source directory: /Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils
# Build directory: /Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/cmake-cache/utils
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-test-runner "ns3.40-test-runner-default")
set_tests_properties(ctest-test-runner PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/utils/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;46;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;0;")
add_test(ctest-bench-scheduler "ns3.40-bench-scheduler-default")
set_tests_properties(ctest-bench-scheduler PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/utils/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;53;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;0;")
add_test(ctest-bench-packets "ns3.40-bench-packets-default")
set_tests_properties(ctest-bench-packets PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/utils/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;61;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;0;")
add_test(ctest-print-introspected-doxygen "ns3.40-print-introspected-doxygen-default")
set_tests_properties(ctest-print-introspected-doxygen PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/utils/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;68;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;0;")
add_test(ctest-perf-io "ns3.40-perf-io-default")
set_tests_properties(ctest-perf-io PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/utils/perf/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;77;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/utils/CMakeLists.txt;0;")
