# CMake generated Testfile for 
# Source directory: /Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples
# Build directory: /Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/cmake-cache/src/sixlowpan/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-example-sixlowpan "ns3.40-example-sixlowpan-default")
set_tests_properties(ctest-example-sixlowpan PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;1;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan "ns3.40-example-ping-lr-wpan-default")
set_tests_properties(ctest-example-ping-lr-wpan PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;12;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-beacon "ns3.40-example-ping-lr-wpan-beacon-default")
set_tests_properties(ctest-example-ping-lr-wpan-beacon PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;23;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;0;")
add_test(ctest-example-ping-lr-wpan-mesh-under "ns3.40-example-ping-lr-wpan-mesh-under-default")
set_tests_properties(ctest-example-ping-lr-wpan-mesh-under PROPERTIES  WORKING_DIRECTORY "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build/src/sixlowpan/examples/" _BACKTRACE_TRIPLES "/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;34;build_lib_example;/Users/bharadwajanandivada/Downloads/ns-allinone-3.40/ns-3.40/src/sixlowpan/examples/CMakeLists.txt;0;")
